# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2" # Use the sha / tag you want to point at
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: url-check
        name: Check URL fragments
        description: "Trigger in case URL fragments get commited"
        entry: "test-.*-dev"
        exclude: ^.pre-commit-config.yaml$
        language: pygrep

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.47.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.31.0
          - typescript@4.3.5
          - "@typescript-eslint/eslint-plugin@4.28.5"
          - "@typescript-eslint/parser@4.28.5"
          - eslint-plugin-vue@7.14.0
          - vue-eslint-parser@7.9.0
          - eslint-config-prettier@8.3.0
