import type { LabeledValue } from "@/types/internal/infos";
import type { Branded } from "@/composables/brand";
import type { MetadataRecord } from "@/composables/collection_tools/getMetadataEntry";

export type CountryCode = Branded<string, "CountryCode">;

export const metadataRecordForCountry: MetadataRecord<
  LabeledValue<CountryCode>
> = {
  ["AC" as CountryCode]: { label: "Ascension" },
  ["AD" as CountryCode]: { label: "Andorra" },
  ["AE" as CountryCode]: { label: "United Arab Emirates" },
  ["AF" as CountryCode]: { label: "Afghanistan" },
  ["AG" as CountryCode]: { label: "Antigua and Barbuda" },
  ["AI" as CountryCode]: { label: "Anguilla" },
  ["AL" as CountryCode]: { label: "Albania" },
  ["AM" as CountryCode]: { label: "Armenia" },
  ["AO" as CountryCode]: { label: "Angola" },
  ["AQ" as CountryCode]: { label: "Antarctica" },
  ["AR" as CountryCode]: { label: "Argentina" },
  ["AS" as CountryCode]: { label: "American Samoa" },
  ["AT" as CountryCode]: { label: "Austria" },
  ["AU" as CountryCode]: { label: "Australia" },
  ["AW" as CountryCode]: { label: "Aruba" },
  ["AX" as CountryCode]: { label: "Åland Islands" },
  ["AZ" as CountryCode]: { label: "Azerbaijan" },
  ["BA" as CountryCode]: { label: "Bosnia and Herzegovina" },
  ["BB" as CountryCode]: { label: "Barbados" },
  ["BD" as CountryCode]: { label: "Bangladesh" },
  ["BE" as CountryCode]: { label: "Belgium" },
  ["BF" as CountryCode]: { label: "Burkina Faso" },
  ["BG" as CountryCode]: { label: "Bulgaria" },
  ["BH" as CountryCode]: { label: "Bahrain" },
  ["BI" as CountryCode]: { label: "Burundi" },
  ["BJ" as CountryCode]: { label: "Benin" },
  ["BL" as CountryCode]: { label: "Saint Barthélemy" },
  ["BM" as CountryCode]: { label: "Bermuda" },
  ["BN" as CountryCode]: { label: "Brunei Darussalam" },
  ["BO" as CountryCode]: { label: "Bolivia" },
  ["BQ" as CountryCode]: { label: "Bonaire" },
  ["BR" as CountryCode]: { label: "Brazil" },
  ["BS" as CountryCode]: { label: "Bahamas" },
  ["BT" as CountryCode]: { label: "Bhutan" },
  ["BV" as CountryCode]: { label: "Bouvet Island" },
  ["BW" as CountryCode]: { label: "Botswana" },
  ["BY" as CountryCode]: { label: "Belarus" },
  ["BZ" as CountryCode]: { label: "Belize" },
  ["CA" as CountryCode]: { label: "Canada" },
  ["CC" as CountryCode]: { label: "Cocos (Keeling) Islands" },
  ["CD" as CountryCode]: { label: "Congo (Democratic Republic of the)" },
  ["CF" as CountryCode]: { label: "Central African Republic" },
  ["CG" as CountryCode]: { label: "Congo" },
  ["CH" as CountryCode]: { label: "Switzerland" },
  ["CI" as CountryCode]: { label: "Côte d'Ivoire" },
  ["CK" as CountryCode]: { label: "Cook Islands" },
  ["CL" as CountryCode]: { label: "Chile" },
  ["CM" as CountryCode]: { label: "Cameroon" },
  ["CN" as CountryCode]: { label: "China" },
  ["CO" as CountryCode]: { label: "Colombia" },
  ["CP" as CountryCode]: { label: "Clipperton" },
  ["CR" as CountryCode]: { label: "Costa Rica" },
  ["CU" as CountryCode]: { label: "Cuba" },
  ["CV" as CountryCode]: { label: "Cabo Verde" },
  ["CW" as CountryCode]: { label: "Curaçao" },
  ["CX" as CountryCode]: { label: "Christmas Island" },
  ["CY" as CountryCode]: { label: "Cyprus" },
  ["CZ" as CountryCode]: { label: "Czechia" },
  ["DE" as CountryCode]: { label: "Germany" },
  ["DG" as CountryCode]: { label: "Diego Garcia" },
  ["DJ" as CountryCode]: { label: "Djibouti" },
  ["DK" as CountryCode]: { label: "Denmark" },
  ["DM" as CountryCode]: { label: "Dominica" },
  ["DO" as CountryCode]: { label: "Dominican Republic" },
  ["DZ" as CountryCode]: { label: "Algeria" },
  ["EA" as CountryCode]: { label: "Ceuta, Melilla" },
  ["EC" as CountryCode]: { label: "Ecuador" },
  ["EE" as CountryCode]: { label: "Estonia" },
  ["EG" as CountryCode]: { label: "Egypt" },
  ["EH" as CountryCode]: { label: "Western Sahara" },
  ["ER" as CountryCode]: { label: "Eritrea" },
  ["ES" as CountryCode]: { label: "Spain" },
  ["ET" as CountryCode]: { label: "Ethiopia" },
  ["FI" as CountryCode]: { label: "Finland" },
  ["FJ" as CountryCode]: { label: "Fiji" },
  ["FK" as CountryCode]: { label: "Falkland Islands" },
  ["FM" as CountryCode]: { label: "Micronesia" },
  ["FO" as CountryCode]: { label: "Faroe Islands" },
  ["FR" as CountryCode]: { label: "France" },
  ["GA" as CountryCode]: { label: "Gabon" },
  ["GB" as CountryCode]: { label: "United Kingdom" },
  ["GD" as CountryCode]: { label: "Grenada" },
  ["GE" as CountryCode]: { label: "Georgia" },
  ["GF" as CountryCode]: { label: "French Guiana" },
  ["GG" as CountryCode]: { label: "Guernsey" },
  ["GH" as CountryCode]: { label: "Ghana" },
  ["GI" as CountryCode]: { label: "Gibraltar" },
  ["GL" as CountryCode]: { label: "Greenland" },
  ["GM" as CountryCode]: { label: "Gambia" },
  ["GN" as CountryCode]: { label: "Guinea" },
  ["GP" as CountryCode]: { label: "Guadeloupe" },
  ["GQ" as CountryCode]: { label: "Equatorial Guinea" },
  ["GR" as CountryCode]: { label: "Greece" },
  ["GS" as CountryCode]: {
    label: "South Georgia and the South Sandwich Islands",
  },
  ["GT" as CountryCode]: { label: "Guatemala" },
  ["GU" as CountryCode]: { label: "Guam" },
  ["GW" as CountryCode]: { label: "Guinea-Bissau" },
  ["GY" as CountryCode]: { label: "Guyana" },
  ["HK" as CountryCode]: { label: "Hong Kong" },
  ["HM" as CountryCode]: { label: "Heard Island and McDonald Islands" },
  ["HN" as CountryCode]: { label: "Honduras" },
  ["HR" as CountryCode]: { label: "Croatia" },
  ["HT" as CountryCode]: { label: "Haiti" },
  ["HU" as CountryCode]: { label: "Hungary" },
  ["IC" as CountryCode]: { label: "Kanarische Inseln" },
  ["ID" as CountryCode]: { label: "Indonesia" },
  ["IE" as CountryCode]: { label: "Ireland" },
  ["IL" as CountryCode]: { label: "Israel" },
  ["IM" as CountryCode]: { label: "Isle of Man" },
  ["IN" as CountryCode]: { label: "India" },
  ["IO" as CountryCode]: { label: "British Indian Ocean Territory" },
  ["IQ" as CountryCode]: { label: "Iraq" },
  ["IR" as CountryCode]: { label: "Iran" },
  ["IS" as CountryCode]: { label: "Iceland" },
  ["IT" as CountryCode]: { label: "Italy" },
  ["JE" as CountryCode]: { label: "Jersey" },
  ["JM" as CountryCode]: { label: "Jamaica" },
  ["JO" as CountryCode]: { label: "Jordan" },
  ["JP" as CountryCode]: { label: "Japan" },
  ["KE" as CountryCode]: { label: "Kenya" },
  ["KG" as CountryCode]: { label: "Kyrgyzstan" },
  ["KH" as CountryCode]: { label: "Cambodia" },
  ["KI" as CountryCode]: { label: "Kiribati" },
  ["KM" as CountryCode]: { label: "Comoros" },
  ["KN" as CountryCode]: { label: "Saint Kitts and Nevis" },
  ["KP" as CountryCode]: { label: "North Korea" },
  ["KR" as CountryCode]: { label: "South Korea" },
  ["KW" as CountryCode]: { label: "Kuwait" },
  ["KY" as CountryCode]: { label: "Cayman Islands" },
  ["KZ" as CountryCode]: { label: "Kazakhstan" },
  ["LA" as CountryCode]: { label: "Lao" },
  ["LB" as CountryCode]: { label: "Lebanon" },
  ["LC" as CountryCode]: { label: "Saint Lucia" },
  ["LI" as CountryCode]: { label: "Liechtenstein" },
  ["LK" as CountryCode]: { label: "Sri Lanka" },
  ["LR" as CountryCode]: { label: "Liberia" },
  ["LS" as CountryCode]: { label: "Lesotho" },
  ["LT" as CountryCode]: { label: "Lithuania" },
  ["LU" as CountryCode]: { label: "Luxembourg" },
  ["LV" as CountryCode]: { label: "Latvia" },
  ["LY" as CountryCode]: { label: "Libya" },
  ["MA" as CountryCode]: { label: "Morocco" },
  ["MC" as CountryCode]: { label: "Monaco" },
  ["MD" as CountryCode]: { label: "Moldova" },
  ["ME" as CountryCode]: { label: "Montenegro" },
  ["MF" as CountryCode]: { label: "Saint Martin (French part)" },
  ["MG" as CountryCode]: { label: "Madagascar" },
  ["MH" as CountryCode]: { label: "Marshall Islands" },
  ["MK" as CountryCode]: { label: "North Macedonia" },
  ["ML" as CountryCode]: { label: "Mali" },
  ["MM" as CountryCode]: { label: "Myanmar" },
  ["MN" as CountryCode]: { label: "Mongolia" },
  ["MO" as CountryCode]: { label: "Macao" },
  ["MP" as CountryCode]: { label: "Northern Mariana Islands" },
  ["MQ" as CountryCode]: { label: "Martinique" },
  ["MR" as CountryCode]: { label: "Mauritania" },
  ["MS" as CountryCode]: { label: "Montserrat" },
  ["MT" as CountryCode]: { label: "Malta" },
  ["MU" as CountryCode]: { label: "Mauritius" },
  ["MV" as CountryCode]: { label: "Maldives" },
  ["MW" as CountryCode]: { label: "Malawi" },
  ["MX" as CountryCode]: { label: "Mexico" },
  ["MY" as CountryCode]: { label: "Malaysia" },
  ["MZ" as CountryCode]: { label: "Mozambique" },
  ["NA" as CountryCode]: { label: "Namibia" },
  ["NC" as CountryCode]: { label: "New Caledonia" },
  ["NE" as CountryCode]: { label: "Niger" },
  ["NF" as CountryCode]: { label: "Norfolk Island" },
  ["NG" as CountryCode]: { label: "Nigeria" },
  ["NI" as CountryCode]: { label: "Nicaragua" },
  ["NL" as CountryCode]: { label: "Netherlands" },
  ["NO" as CountryCode]: { label: "Norway" },
  ["NP" as CountryCode]: { label: "Nepal" },
  ["NR" as CountryCode]: { label: "Nauru" },
  ["NU" as CountryCode]: { label: "Niue" },
  ["NZ" as CountryCode]: { label: "New Zealand" },
  ["OM" as CountryCode]: { label: "Oman" },
  ["PA" as CountryCode]: { label: "Panama" },
  ["PE" as CountryCode]: { label: "Peru" },
  ["PF" as CountryCode]: { label: "French Polynesia" },
  ["PG" as CountryCode]: { label: "Papua New Guinea" },
  ["PH" as CountryCode]: { label: "Philippines" },
  ["PK" as CountryCode]: { label: "Pakistan" },
  ["PL" as CountryCode]: { label: "Poland" },
  ["PM" as CountryCode]: { label: "Saint Pierre and Miquelon" },
  ["PN" as CountryCode]: { label: "Pitcairn" },
  ["PR" as CountryCode]: { label: "Puerto Rico" },
  ["PS" as CountryCode]: { label: "Palestine, State of" },
  ["PT" as CountryCode]: { label: "Portugal" },
  ["PW" as CountryCode]: { label: "Palau" },
  ["PY" as CountryCode]: { label: "Paraguay" },
  ["QA" as CountryCode]: { label: "Qatar" },
  ["RE" as CountryCode]: { label: "Réunion" },
  ["RO" as CountryCode]: { label: "Romania" },
  ["RS" as CountryCode]: { label: "Serbia" },
  ["RU" as CountryCode]: { label: "Russian Federation" },
  ["RW" as CountryCode]: { label: "Rwanda" },
  ["SA" as CountryCode]: { label: "Saudi Arabia" },
  ["SB" as CountryCode]: { label: "Solomon Islands" },
  ["SC" as CountryCode]: { label: "Seychelles" },
  ["SD" as CountryCode]: { label: "Sudan" },
  ["SE" as CountryCode]: { label: "Sweden" },
  ["SG" as CountryCode]: { label: "Singapore" },
  ["SH" as CountryCode]: { label: "Saint Helena" },
  ["SI" as CountryCode]: { label: "Slovenia" },
  ["SJ" as CountryCode]: { label: "Svalbard" },
  ["SK" as CountryCode]: { label: "Slovakia" },
  ["SL" as CountryCode]: { label: "Sierra Leone" },
  ["SM" as CountryCode]: { label: "San Marino" },
  ["SN" as CountryCode]: { label: "Senegal" },
  ["SO" as CountryCode]: { label: "Somalia" },
  ["SR" as CountryCode]: { label: "Suriname" },
  ["SS" as CountryCode]: { label: "South Sudan" },
  ["ST" as CountryCode]: { label: "Sao Tome and Principe" },
  ["SV" as CountryCode]: { label: "El Salvador" },
  ["SX" as CountryCode]: { label: "Sint Maarten (Dutch part)" },
  ["SY" as CountryCode]: { label: "Syrian Arab Republic" },
  ["SZ" as CountryCode]: { label: "Eswatini" },
  ["TA" as CountryCode]: { label: "Tristan da Cunha" },
  ["TC" as CountryCode]: { label: "Turks and Caicos Islands" },
  ["TD" as CountryCode]: { label: "Chad" },
  ["TF" as CountryCode]: { label: "French Southern Territories" },
  ["TG" as CountryCode]: { label: "Togo" },
  ["TH" as CountryCode]: { label: "Thailand" },
  ["TJ" as CountryCode]: { label: "Tajikistan" },
  ["TK" as CountryCode]: { label: "Tokelau" },
  ["TL" as CountryCode]: { label: "Timor-Leste" },
  ["TM" as CountryCode]: { label: "Turkmenistan" },
  ["TN" as CountryCode]: { label: "Tunisia" },
  ["TO" as CountryCode]: { label: "Tonga" },
  ["TR" as CountryCode]: { label: "Türkiye" },
  ["TT" as CountryCode]: { label: "Trinidad and Tobago" },
  ["TV" as CountryCode]: { label: "Tuvalu" },
  ["TW" as CountryCode]: { label: "Taiwan" },
  ["TZ" as CountryCode]: { label: "Tanzania" },
  ["UA" as CountryCode]: { label: "Ukraine" },
  ["UG" as CountryCode]: { label: "Uganda" },
  ["UM" as CountryCode]: { label: "United States Minor Outlying Islands" },
  ["US" as CountryCode]: { label: "United States of America" },
  ["UY" as CountryCode]: { label: "Uruguay" },
  ["UZ" as CountryCode]: { label: "Uzbekistan" },
  ["VA" as CountryCode]: { label: "Holy See (Vatican City State)" },
  ["VC" as CountryCode]: { label: "Saint Vincent and the Grenadines" },
  ["VE" as CountryCode]: { label: "Venezuela" },
  ["VG" as CountryCode]: { label: "Virgin Islands (British)" },
  ["VI" as CountryCode]: { label: "Virgin Islands (U.S.)" },
  ["VN" as CountryCode]: { label: "Viet Nam" },
  ["VU" as CountryCode]: { label: "Vanuatu" },
  ["WF" as CountryCode]: { label: "Wallis and Futuna" },
  ["WS" as CountryCode]: { label: "Samoa" },
  ["YE" as CountryCode]: { label: "Yemen" },
  ["YT" as CountryCode]: { label: "Mayotte" },
  ["ZA" as CountryCode]: { label: "South Africa" },
  ["ZM" as CountryCode]: { label: "Zambia" },
  ["ZW" as CountryCode]: { label: "Zimbabwe" },
};
