import { deepCopy } from "@/composables/state/deepCopy";
import type { ApiAttendeeInfo } from "@/types/external";
import { transformAttendee } from "@/composables/services/attendee/transformAttendee";
import type { TransformedAttendeeInfo } from "@/types/internal";

const dummyData: ApiAttendeeInfo[] = [
  {
    id: 8,
    badge_id: "8J",
    nickname: "Entry",
    first_name: "Software",
    last_name: "Hardware",
    country: "AL",
    birthday: "2005-09-03",
    pronouns: "She/Her",
    spoken_languages: "de,no,nb,ur",
    registration_language: "de-DE",
    flags: "anon",
    options: "music",
    packages: "room-none,tshirt,day-tue,dealer-half",
    status: "checked in",
    total_dues: 14000,
    payment_balance: 0,
    current_dues: 14000,
    spoken_languages_list: ["de", "no", "nb", "ur"],
    flags_list: ["anon"],
    options_list: ["music"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "tshirt",
        count: 1,
      },
      {
        name: "day-tue",
        count: 1,
      },
      {
        name: "dealer-half",
        count: 1,
      },
    ],
  },
  {
    id: 14,
    badge_id: "14U",
    nickname: "Huhu",
    first_name: "First",
    last_name: "Last",
    country: "DE",
    birthday: "1984-10-02",
    pronouns: "He/Him",
    tshirt_size: "XXL",
    spoken_languages: "da,en,fa",
    registration_language: "de-DE",
    flags: "hc,anon,digi-book,terms-accepted,ev,skip_ban_check,staff",
    options: "art",
    packages:
      "room-none,tshirt,day-sun,dealer-half,boat-trip,boat-vip,boat-benefactor,artshow-table,artshow-panel",
    status: "approved",
    total_dues: 31000,
    payment_balance: 0,
    current_dues: 31000,
    spoken_languages_list: ["da", "en", "fa"],
    flags_list: [
      "hc",
      "anon",
      "digi-book",
      "terms-accepted",
      "ev",
      "skip_ban_check",
      "staff",
    ],
    options_list: ["art"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "tshirt",
        count: 1,
      },
      {
        name: "day-sun",
        count: 1,
      },
      {
        name: "dealer-half",
        count: 1,
      },
      {
        name: "boat-trip",
        count: 1,
      },
      {
        name: "boat-vip",
        count: 1,
      },
      {
        name: "boat-benefactor",
        count: 1,
      },
      {
        name: "artshow-table",
        count: 1,
      },
      {
        name: "artshow-panel",
        count: 1,
      },
    ],
  },
  {
    id: 33,
    badge_id: "33T",
    nickname: "Cerra",
    first_name: "Seven",
    last_name: "Quantum",
    country: "AO",
    birthday: "2002-08-11",
    pronouns: "He/Him",
    tshirt_size: "M",
    spoken_languages: "ach",
    registration_language: "de-DE",
    flags: "anon,terms-accepted",
    options: "",
    packages: "room-none,attendance",
    status: "partially paid",
    total_dues: 12000,
    payment_balance: 1000,
    current_dues: 11000,
    spoken_languages_list: ["ach"],
    flags_list: ["anon", "terms-accepted"],
    options_list: [],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
    ],
  },
  {
    id: 34,
    badge_id: "34V",
    nickname: "noname",
    first_name: "Terra",
    last_name: "Beta",
    country: "BE",
    birthday: "1999-04-05",
    pronouns: "They/Them",
    tshirt_size: "M",
    spoken_languages: "zh",
    registration_language: "en-US",
    flags: "terms-accepted",
    options: "music,suit",
    packages: "room-none,attendance,stage,sponsor,dealer-double",
    status: "approved",
    total_dues: 32500,
    payment_balance: 0,
    current_dues: 32500,
    spoken_languages_list: ["zh"],
    flags_list: ["terms-accepted"],
    options_list: ["music", "suit"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
      {
        name: "dealer-double",
        count: 1,
      },
    ],
  },
  {
    id: 35,
    badge_id: "35H",
    nickname: "Weird",
    first_name: "Ban",
    last_name: "Al",
    country: "DE",
    birthday: "1974-01-11",
    pronouns: "Shi/Hir",
    spoken_languages: "de",
    registration_language: "en-US",
    flags: "anon,terms-accepted,skip_ban_check",
    options: "anim,art,music,suit",
    packages: "room-none,day-tue,dealer-double,boat-trip",
    status: "paid",
    total_dues: 31250,
    payment_balance: 31250,
    current_dues: 0,
    spoken_languages_list: ["de"],
    flags_list: ["anon", "terms-accepted", "skip_ban_check"],
    options_list: ["anim", "art", "music", "suit"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "day-tue",
        count: 1,
      },
      {
        name: "dealer-double",
        count: 1,
      },
      {
        name: "boat-trip",
        count: 1,
      },
    ],
  },
  {
    id: 38,
    badge_id: "38P",
    nickname: "Dennis",
    first_name: "Darren",
    last_name: "Ditto",
    country: "CH",
    birthday: "2005-09-04",
    pronouns: "She/Her",
    tshirt_size: "M",
    spoken_languages: "de",
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    options: "music",
    packages: "room-none,attendance,stage,sponsor",
    status: "paid",
    total_dues: 25000,
    payment_balance: 25000,
    current_dues: 0,
    spoken_languages_list: ["de"],
    flags_list: ["anon", "terms-accepted"],
    options_list: ["music"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
    ],
  },
  {
    id: 39,
    badge_id: "39Q",
    nickname: "Merp",
    first_name: "Merp",
    last_name: "Derp",
    country: "DE",
    birthday: "1988-12-15",
    spoken_languages: "de,en",
    registration_language: "de-DE",
    flags: "anon,digi-book,terms-accepted",
    options: "",
    packages: "room-none,attendance,stage,boat-trip,boat-vip",
    status: "approved",
    total_dues: 18000,
    payment_balance: 0,
    current_dues: 18000,
    spoken_languages_list: ["de", "en"],
    flags_list: ["anon", "digi-book", "terms-accepted"],
    options_list: [],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "boat-trip",
        count: 1,
      },
      {
        name: "boat-vip",
        count: 1,
      },
    ],
  },
  {
    id: 40,
    badge_id: "40K",
    nickname: "Catbert",
    first_name: "X",
    last_name: "Mister",
    country: "DE",
    birthday: "1979-11-16",
    pronouns: "He/Him",
    tshirt_size: "L",
    spoken_languages: "de",
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    options: "art,anim",
    packages: "room-none,attendance,stage,sponsor2",
    status: "paid",
    total_dues: 32800,
    payment_balance: 32800,
    current_dues: 0,
    spoken_languages_list: ["de"],
    flags_list: ["anon", "terms-accepted"],
    options_list: ["art", "anim"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor2",
        count: 1,
      },
    ],
  },
  {
    id: 43,
    badge_id: "43S",
    nickname: "Billy",
    first_name: "William",
    last_name: "Doe",
    country: "DE",
    birthday: "1977-06-16",
    pronouns: "She/Her",
    tshirt_size: "L",
    spoken_languages: "de",
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    options: "",
    packages: "room-none,attendance,stage,sponsor",
    status: "paid",
    total_dues: 20500,
    payment_balance: 21500,
    current_dues: -1000,
    spoken_languages_list: ["de"],
    flags_list: ["anon", "terms-accepted"],
    options_list: [],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
    ],
  },
  {
    id: 44,
    badge_id: "44D",
    nickname: "Tester",
    first_name: "Dohn",
    last_name: "Joe",
    country: "AI",
    birthday: "1983-06-05",
    tshirt_size: "M",
    spoken_languages: "ak",
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    options: "",
    packages: "room-none,attendance,stage,sponsor,dealer-double",
    status: "partially paid",
    total_dues: 29500,
    payment_balance: 19500,
    current_dues: 10000,
    spoken_languages_list: ["ak"],
    flags_list: ["anon", "terms-accepted"],
    options_list: [],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
      {
        name: "dealer-double",
        count: 1,
      },
    ],
  },
  {
    id: 45,
    badge_id: "45A",
    nickname: "NotNick2",
    first_name: "Registry",
    last_name: "Smith",
    country: "DE",
    birthday: "1987-06-11",
    tshirt_size: "XL",
    spoken_languages: "de",
    registration_language: "en-US",
    flags: "anon,terms-accepted,staff,director",
    options: "art,anim",
    packages:
      "room-none,attendance,stage,sponsor2,boat-trip,boat-vip,artshow-panel",
    status: "partially paid",
    total_dues: 42500,
    payment_balance: 20000,
    current_dues: 22500,
    spoken_languages_list: ["de"],
    flags_list: ["anon", "terms-accepted", "staff", "director"],
    options_list: ["art", "anim"],
    packages_list: [
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "sponsor2",
        count: 1,
      },
      {
        name: "boat-trip",
        count: 1,
      },
      {
        name: "boat-vip",
        count: 1,
      },
      {
        name: "artshow-panel",
        count: 1,
      },
    ],
  },
  {
    id: 3,
    badge_id: "3L",
    nickname: "Lambda \u0633\u0646\u062c\u0627\u0628",
    first_name: "Filler",
    last_name: "M\u00fcller",
    country: "DE",
    birthday: "1972-11-07",
    pronouns: "X\u00fc/X\u00e4m",
    tshirt_size: "XL",
    spoken_languages: "de,en",
    spoken_languages_list: ["de", "en"],
    registration_language: "en-US",
    flags: "anon,ev,terms-accepted",
    flags_list: ["anon", "ev", "terms-accepted"],
    options: "",
    packages: "attendance,early,room-none,sponsor,stage,dealer-fullplus",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "early",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "dealer-fullplus",
        count: 1,
      },
    ],
    status: "paid",
    total_dues: 40000,
    payment_balance: 40000,
    current_dues: 0,
    options_list: [],
  },
  {
    id: 4,
    badge_id: "4Y",
    nickname: "Garry",
    first_name: "Larry",
    last_name: "Harry",
    country: "DE",
    birthday: "1985-02-14",
    pronouns: "Shi/Hir",
    tshirt_size: "L",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "de-DE",
    flags: "digi-book,hc,terms-accepted",
    flags_list: ["digi-book", "hc", "terms-accepted"],
    options: "anim,art,music,suit",
    options_list: ["anim", "art", "music", "suit"],
    packages: "attendance,early,room-none,stage,tshirt",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "early",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "tshirt",
        count: 1,
      },
    ],
    status: "paid",
    total_dues: 17000,
    payment_balance: 17000,
    current_dues: 0,
  },
  {
    id: 29,
    badge_id: "29B",
    nickname: "Stefan",
    first_name: "Dummy",
    last_name: "Nome",
    country: "HT",
    birthday: "1906-10-28",
    pronouns: "he/him",
    tshirt_size: "wXL",
    spoken_languages: "cy,de,ja,tlh",
    spoken_languages_list: ["cy", "de", "ja", "tlh"],
    registration_language: "en-US",
    flags: "digi-book,ev,hc,terms-accepted",
    flags_list: ["digi-book", "ev", "hc", "terms-accepted"],
    options: "art,suit",
    options_list: ["art", "suit"],
    packages: "attendance,room-none,sponsor2,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "sponsor2",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 36500,
    payment_balance: 0,
    current_dues: 36500,
  },
  {
    id: 6893,
    badge_id: "6893W",
    nickname: "Eagle",
    first_name: "Baldur",
    last_name: "Tor",
    country: "AD",
    birthday: "1970-01-01",
    tshirt_size: "S",
    spoken_languages: "cy",
    spoken_languages_list: ["cy"],
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    flags_list: ["anon", "terms-accepted"],
    options: "",
    packages: "attendance,early,room-none,sponsor,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "early",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "sponsor",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 25000,
    payment_balance: 0,
    current_dues: 25000,
    options_list: [],
  },
  {
    id: 6896,
    badge_id: "6896D",
    nickname: "Wolf",
    first_name: "Dohn",
    last_name: "Joe",
    country: "WF",
    birthday: "1940-02-16",
    pronouns: "He/Him",
    spoken_languages: "ur",
    spoken_languages_list: ["ur"],
    registration_language: "en-US",
    flags: "anon,ev,terms-accepted",
    flags_list: ["anon", "ev", "terms-accepted"],
    options: "",
    packages: "attendance,early,room-none,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "early",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "checked in",
    total_dues: 15000,
    payment_balance: 15000,
    current_dues: 0,
    options_list: [],
  },
  {
    id: 6898,
    badge_id: "6898F",
    nickname: "Merp",
    first_name: "Merp",
    last_name: "Derp",
    country: "DE",
    birthday: "1998-02-01",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "de-DE",
    flags: "anon,ev,terms-accepted",
    flags_list: ["anon", "ev", "terms-accepted"],
    options: "",
    packages: "attendance,room-none,stage,boat-trip,boat-vip",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "boat-trip",
        count: 1,
      },
      {
        name: "boat-vip",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 23000,
    payment_balance: 0,
    current_dues: 23000,
    options_list: [],
  },
  {
    id: 6899,
    badge_id: "6899C",
    nickname: "Viktor",
    first_name: "Muster",
    last_name: "B",
    country: "DE",
    birthday: "1972-11-06",
    pronouns: "They/Them",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "en-US",
    flags: "anon,digi-book,ev,terms-accepted",
    flags_list: ["anon", "digi-book", "ev", "terms-accepted"],
    options: "anim,art,music,suit",
    options_list: ["anim", "art", "music", "suit"],
    packages: "attendance,late,room-none,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "late",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 18000,
    payment_balance: 0,
    current_dues: 18000,
  },
  {
    id: 6900,
    badge_id: "6900X",
    nickname: "regtest5",
    first_name: "Test",
    last_name: "Reg",
    country: "DE",
    birthday: "1999-06-09",
    pronouns: "She/Her",
    tshirt_size: "L",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "de-DE",
    flags: "anon,digi-book,terms-accepted",
    flags_list: ["anon", "digi-book", "terms-accepted"],
    options: "anim,art,music,suit",
    options_list: ["anim", "art", "music", "suit"],
    packages: "attendance,late,room-none,stage,tshirt",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "late",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
      {
        name: "tshirt",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 20000,
    payment_balance: 0,
    current_dues: 20000,
  },
  {
    id: 6902,
    badge_id: "6902P",
    nickname: "Honner",
    first_name: "John",
    last_name: "Doe",
    country: "AQ",
    birthday: "1970-01-01",
    spoken_languages: "de,en",
    spoken_languages_list: ["de", "en"],
    registration_language: "en-US",
    flags: "terms-accepted",
    flags_list: ["terms-accepted"],
    options: "",
    packages: "attendance,late,room-none,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "late",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 18000,
    payment_balance: 0,
    current_dues: 18000,
    options_list: [],
  },
  {
    id: 6903,
    badge_id: "6903Q",
    nickname: "Regtest4",
    first_name: "Test4",
    last_name: "LTest4",
    country: "DE",
    birthday: "1974-11-07",
    pronouns: "He/Him",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    flags_list: ["anon", "terms-accepted"],
    options: "",
    packages: "attendance,late,room-none,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "late",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 18000,
    payment_balance: 0,
    current_dues: 18000,
    options_list: [],
  },
  {
    id: 6904,
    badge_id: "6904K",
    nickname: "regtest3",
    first_name: "Michael",
    last_name: "Tester",
    country: "DE",
    birthday: "1970-06-06",
    pronouns: "Shi/Hir",
    spoken_languages: "de",
    spoken_languages_list: ["de"],
    registration_language: "en-US",
    flags: "anon,terms-accepted",
    flags_list: ["anon", "terms-accepted"],
    options: "anim,art,music,suit",
    options_list: ["anim", "art", "music", "suit"],
    packages: "attendance,late,room-none,stage",
    packages_list: [
      {
        name: "attendance",
        count: 1,
      },
      {
        name: "late",
        count: 1,
      },
      {
        name: "room-none",
        count: 1,
      },
      {
        name: "stage",
        count: 1,
      },
    ],
    status: "approved",
    total_dues: 18000,
    payment_balance: 0,
    current_dues: 18000,
  },
];

export function getApiAttendeeInfo(): TransformedAttendeeInfo[] {
  return deepCopy(dummyData).map(transformAttendee);
}
