upstream onsite-backend {
    server onsite-backend:8001;
}

server {
    listen       8000;
    listen  [::]:8000;
    server_name  localhost;

    add_header Content-Security-Policy "default-src 'self'; img-src * data: blob:; font-src * data: blob:;" always;

    location ~ (/api/.*) {
        proxy_pass http://onsite-backend$1$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        client_max_body_size 20m;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Try exact match, then .html file, then 404
        try_files $uri $uri/ $uri.html $uri/index.html =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
