const dummyData = [
    {
        id: 8,
        badge_id: "8J",
        nickname: "Regtest4 The One And Only",
        first_name: "Reg",
        last_name: "Test4",
        country: "AL",
        birthday: "2005-09-03",
        pronouns: "She/Her",
        spoken_languages: "de,no,nb,ur",
        registration_language: "de-DE",
        flags: "anon",
        options: "music",
        packages: "room-none,tshirt,day-tue,dealer-half",
        status: "checked in",
        total_dues: 14000,
        payment_balance: 0,
        current_dues: 14000,
    },
    {
        id: 14,
        badge_id: "14U",
        nickname: "Rakan",
        first_name: "Nakar",
        last_name: "xyz",
        country: "DE",
        birthday: "1984-10-02",
        pronouns: "He/Him",
        tshirt_size: "XXL",
        spoken_languages: "da,en,fa",
        registration_language: "de-DE",
        flags: "hc,anon,digi-book,terms-accepted,ev,skip_ban_check,staff",
        options: "art",
        packages: "room-none,tshirt,day-sun,dealer-half,boat-trip,boat-vip,boat-benefactor,artshow-table,artshow-panel",
        status: "approved",
        total_dues: 31000,
        payment_balance: 0,
        current_dues: 31000,
    },
    {
        id: 33,
        badge_id: "33T",
        nickname: "Jumpy8",
        first_name: "Jp",
        last_name: "77",
        country: "AO",
        birthday: "2002-08-11",
        pronouns: "He/Him",
        tshirt_size: "M",
        spoken_languages: "ach",
        registration_language: "de-DE",
        flags: "anon,terms-accepted",
        options: "",
        packages: "room-none,attendance",
        status: "partially paid",
        total_dues: 12000,
        payment_balance: 1000,
        current_dues: 11000,
    },
    {
        id: 34,
        badge_id: "34V",
        nickname: "notrylli",
        first_name: "asdgdowqfeqf",
        last_name: "wefwcc",
        country: "BE",
        birthday: "1999-04-05",
        pronouns: "They/Them",
        tshirt_size: "M",
        spoken_languages: "zh",
        registration_language: "en-US",
        flags: "terms-accepted",
        options: "music,suit",
        packages: "room-none,attendance,stage,sponsor,dealer-double",
        status: "approved",
        total_dues: 32500,
        payment_balance: 0,
        current_dues: 32500,
    },
    {
        id: 35,
        badge_id: "35H",
        nickname: "ARegtest1",
        first_name: "Ban",
        last_name: "Tester",
        country: "DE",
        birthday: "1974-01-11",
        pronouns: "Shi/Hir",
        spoken_languages: "de",
        registration_language: "en-US",
        flags: "anon,terms-accepted,skip_ban_check",
        options: "anim,art,music,suit",
        packages: "room-none,day-tue,dealer-double,boat-trip",
        status: "paid",
        total_dues: 31250,
        payment_balance: 31250,
        current_dues: 0,
    },
    {
        id: 38,
        badge_id: "38P",
        nickname: "Regtest2",
        first_name: "J2",
        last_name: "D2",
        country: "CH",
        birthday: "2005-09-04",
        pronouns: "She/Her",
        tshirt_size: "M",
        spoken_languages: "de",
        registration_language: "en-US",
        flags: "anon,terms-accepted",
        options: "music",
        packages: "room-none,attendance,stage,sponsor",
        status: "paid",
        total_dues: 25000,
        payment_balance: 25000,
        current_dues: 0,
    },
    {
        id: 39,
        badge_id: "39Q",
        nickname: "Merp",
        first_name: "Merp",
        last_name: "Derp",
        country: "DE",
        birthday: "1988-12-15",
        spoken_languages: "de,en",
        registration_language: "de-DE",
        flags: "anon,digi-book,terms-accepted",
        options: "",
        packages: "room-none,attendance,stage,boat-trip,boat-vip",
        status: "approved",
        total_dues: 18000,
        payment_balance: 0,
        current_dues: 18000,
    },
    {
        id: 40,
        badge_id: "40K",
        nickname: "Jumpy11",
        first_name: "J",
        last_name: "Squirrel",
        country: "DE",
        birthday: "1979-11-16",
        pronouns: "He/Him",
        tshirt_size: "L",
        spoken_languages: "de",
        registration_language: "en-US",
        flags: "anon,terms-accepted",
        options: "art,anim",
        packages: "room-none,attendance,stage,sponsor2",
        status: "paid",
        total_dues: 32800,
        payment_balance: 32800,
        current_dues: 0,
    },
    {
        id: 43,
        badge_id: "43S",
        nickname: "Regtest3",
        first_name: "Regtest3",
        last_name: "Doe",
        country: "DE",
        birthday: "1977-06-16",
        pronouns: "She/Her",
        tshirt_size: "L",
        spoken_languages: "de",
        registration_language: "en-US",
        flags: "anon,terms-accepted",
        options: "",
        packages: "room-none,attendance,stage,sponsor",
        status: "paid",
        total_dues: 20500,
        payment_balance: 21500,
        current_dues: -1000,
    },
    {
        id: 44,
        badge_id: "44D",
        nickname: "test",
        first_name: "Dohn",
        last_name: "Joe",
        country: "AI",
        birthday: "1983-06-05",
        tshirt_size: "M",
        spoken_languages: "ak",
        registration_language: "en-US",
        flags: "anon,terms-accepted",
        options: "",
        packages: "room-none,attendance,stage,sponsor,dealer-double",
        status: "partially paid",
        total_dues: 29500,
        payment_balance: 19500,
        current_dues: 10000,
    },
    {
        id: 45,
        badge_id: "45A",
        nickname: "Regtest4",
        first_name: "Reg",
        last_name: "Test4",
        country: "DE",
        birthday: "1987-06-11",
        tshirt_size: "XL",
        spoken_languages: "de",
        registration_language: "en-US",
        flags: "anon,terms-accepted,staff,director",
        options: "art,anim",
        packages: "room-none,attendance,stage,sponsor2,boat-trip,boat-vip,artshow-panel",
        status: "partially paid",
        total_dues: 42500,
        payment_balance: 20000,
        current_dues: 22500,
    },
];

export function getDummyData() {
    return JSON.parse(JSON.stringify(dummyData));
}
