export const didYouKnowFacts: string[] = [
  'A random "I LOVE YOUR TAIL" can absolutely make someone\'s entire week.',
  'Saying "boop" while booping a snoot increases friendship by approximately 42%.',
  "\"Quickly visiting the Dealers Den\" is a physical impossibility.",
  "*random animal noises*",
  "A fursuit hug has a surprisingly high chance of fixing whatever was wrong five minutes ago.",
  "A well-timed boop can solve at least 67.621% of convention problems.",
  "EF started in 1995 with just 19 furries.",
  "Meow!",
  "Squeak!",
  "Press Escape to reset filters and close dialogs.",
  "Somewhere nearby, a tired staffer is being powered entirely by camaraderie and slushies.",
  "The best con photos are rarely the ones you planned.",
  "There is always room for one more in the cuddle pile.",
  "You can adjust the header and font size from the Theme Settings (gear icon).",
  "You can toggle dark mode from the Theme Settings (gear icon).",
  "You're here. You're among friends. You help to make this con amazing. That's awesome!",
  ...Array(10).fill("Awoooo!"),
];
